server:
  port: 8081

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/abernathy_patient?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true